version: '3'

services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - kin-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kin-news
      - POSTGRES_USER=kin-news-user
      - POSTGRES_PASSWORD=kin-news-password

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - kin-network

networks:
  kin-network:
    external:
      name: kin-network

volumes:
  pgdata:
  cache:
