version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./etc/kin-news/Dockerfile
    image: "kin-news-api"
    container_name: "kin-news-api"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./etc/kin-news/env/.dev.env
    ports:
      - "8000:8000"
    networks:
      - kin-network
    volumes:
      - ./kin_news_api/api:/app/api
      - ./kin_news_api/config:/app/config
      - ./submodules/kin-news-core/kin_news_core:/app/kin_news_core
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - kin-network
    env_file:
      - ./etc/kin-news/env/.dev.db.env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    env_file:
      - ./etc/kin-news/env/.dev.env
    volumes:
      - cache:/data
    networks:
      - kin-network

networks:
  kin-network:
    external:
      name: kin-network

volumes:
  pgdata:
  cache:
