version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./etc/kin-news/Dockerfile
    image: "kin-news-api"
    container_name: "kin-news-api"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./etc/kin-news/env/.dev.env
    ports:
      - "8000:8000"
    networks:
      - kin-network
    volumes:
      - ./kin_news_api/api:/app/api
      - ./kin_news_api/config:/app/config
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - kin-network
    env_file:
      - ./etc/kin-news/env/.dev.db.env


networks:
  kin-network:
    external:
      name: kin-network

volumes:
  pgdata:
